# Generated by Django 5.1.15 on 2026-07-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='The order number of the lesson inside a course. Left blank, it auto-increments.', null=True),
        ),
    ]
